# vim:set ft=dockerfile:
FROM alpine:3.12

LABEL maintainer="Andrius Kairiukstis <k@andrius.mobi>"

ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1

WORKDIR /app

COPY Gemfile* ./
COPY udash.rb .

RUN apk update \
&&  apk add \
	    docker \
	    ruby \
      less \
&&  apk add --virtual .build-dependencies \
      build-base \
      ruby-dev \
&&  gem install bundler || apk add ruby-bundler \
&&  bundle config build.nokogiri --use-system-libraries \
&&  bundle config git.allow_insecure true \
&&  bundle install \
&&  gem cleanup \
&&  rm -rf /usr/lib/ruby/gems/*/cache/* \
           /var/cache/apk/* \
           /tmp/* \
           /var/tmp/*

EXPOSE 4567

CMD ["bundle", "exec", "./udash.rb"]
